# Generated by Django 4.1.1 on 2022-10-02 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_quizquestion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizcategory',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='quizquestion',
            options={'verbose_name_plural': 'Questions'},
        ),
    ]
